name: codio-publish
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Log into Codio
        id: codio-login
        uses: codio/codio-auth-action@master
        with:
          client-id: ${{ secrets.JAVA_OBJECTS_CLIENT_ID }}
          secret-id: ${{ secrets.JAVA_OBJECTS_SECRET_ID }}
          domain: codio.com

      - name: Checkout
        uses: actions/checkout@v1

      - name: Cleanup
        run: rm -rf .github README.md

      - name: Install Zip
        uses: montudor/action-zip@v0.1.1

      - name: Zip
        run: zip -qq -r ../data.zip .

      - name: Publish to Codio
        uses: codio/codio-book-publish-action@master
        with:
          token: ${{ steps.codio-login.outputs.token }}
          book-id: 61a5efce71eb25b4e2fa2f982c2c33bc
          domain: codio.com
          zip: ../data.zip
          changelog: ${{ github.event.head_commit.message }}